version: '3.8'
services:
  app:
    image: php:8.4-fpm
    container_name: lumora_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    command: bash -c "apt-get update && apt-get install -y git zip unzip libpng-dev libonig-dev libxml2-dev libpq-dev && docker-php-ext-install pdo_pgsql mbstring exif pcntl bcmath gd && php-fpm"

  nginx:
    image: nginx:latest
    container_name: lumora_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:16
    container_name: lumora_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: lumora
      POSTGRES_USER: lumora
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: lumora_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lumora.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmindata:/var/lib/pgadmin

volumes:
  dbdata:
  pgadmindata:
